### ISSUE TITLE
一个不错的动画特效

### ISSUE THREAD

**Issue by justincsd** [tpdjg/tpdjg.github.io#2]
在你的 `index.js` 文件里面可以添加一个语句：
```js
function TypingText({ text }) {
  const [displayText, setDisplayText] = useState('');
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    if (currentIndex < text.length) {
      const timeout = setTimeout(() => {
        setDisplayText(prev => prev + text[currentIndex]);
        setCurrentIndex(prev => prev + 1);
      }, 70); // 每个字符的延迟时间

      return () => clearTimeout(timeout);
    }
  }, [currentIndex, text]);

  return <span className="typing-text">{displayText}</span>;
}
```
一个打字机的动画特效。

同时在 `custom.css` 里面添加这个：
```css
/* 打字机效果 */
@keyframes typing {
  from {
    width: 0
  }

  to {
    width: 100%
  }
}

@keyframes blink {
  50% {
    border-color: transparent
  }
}

.typing-text {
  display: inline-block;
  overflow: hidden;
  white-space: nowrap;
  border-right: 2px solid var(--ifm-color-primary);
  animation:
    typing 3.5s steps(40, end),
    blink .75s step-end infinite;
  margin: 0 auto;
}
```
